nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.6.0.cjs

packageExtensions:
  react-scripts@*:
    peerDependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"

enableGlobalCache: false 