version: '3.8'

services:
  client:
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./apps/client:/app/apps/client
      - /app/apps/client/node_modules
    environment:
      - NODE_ENV=development
      - YARN_VERSION=4.6.0
    depends_on:
      - server

  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/server:/app/apps/server
      - /app/apps/server/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/klimametrix
      - YARN_VERSION=4.6.0
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=klimametrix
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 