services:
  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./apps/server/.env.${NODE_ENV}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    env_file:
      - ./apps/server/.env.${NODE_ENV}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 