name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare yarn@4.6.0 --activate
          yarn install
      - name: Run client tests
        run: |
          cd apps/client
          yarn test --passWithNoTests
      - name: Run server tests
        run: |
          cd apps/server
          yarn test --passWithNoTests

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build client image
        run: docker build -f apps/client/Dockerfile .
      - name: Build server image
        run: docker build -f apps/server/Dockerfile .

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      # Deployment steps will be added later
