name: Sync Client to Deployment Repo

on:
  push:
    branches: [main]
    paths:
      - 'apps/client/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: monorepo

      - uses: actions/checkout@v3
        with:
          repository: mattburnett-repo/klimametrix-client
          path: deploy-repo
          token: ${{ secrets.DEPLOY_PAT }}

      - name: Sync Files
        run: |
          # Clean deployment repo
          cd deploy-repo
          find . -not -path './.git/*' -not -name '.git' -delete

          # Copy client files
          cp -r ../monorepo/apps/client/* ./

          # Create simple package.json
          cat << 'EOF' > package.json
          {
            "name": "klimametrix-client",
            "private": true,
            "version": "0.0.1",
            "type": "module",
            "scripts": {
              "dev": "vite",
              "build": "tsc && vite build",
              "start": "vite preview"
            }
          }
          EOF

          # Commit and push
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Sync from monorepo" && git push)